# Generated by Django 4.0.3 on 2022-06-19 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_system', '0002_alter_todo_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='create_date',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='on_date',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
