# Generated by Django 4.0.3 on 2022-06-22 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_system', '0005_userverification_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userverification',
            name='user',
        ),
    ]
