# Generated by Django 4.0.3 on 2022-06-22 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_system', '0006_remove_userverification_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userverification',
            name='otp',
            field=models.CharField(default='', max_length=6),
        ),
    ]
